filebeat.registry_file: /usr/share/filebeat/data/registry
filebeat.config.prospectors:
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: true
output.elasticsearch:
  hosts: ["elasticsearch:9200"]