heartbeat.monitors:
- type: icmp
  schedule: '*/5 * * * * * *'
  hosts: ["filebeat","metricbeat","packetbeat","elasticsearch","kibana","logstash","apache2","nginx","mysql"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 16s
  wait: 1s
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://elasticsearch:9200"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  username: '${ES_USERNAME:elastic}'
  password: '${ES_PASSWORD:changeme}'
  check.request:
    method: "GET"
  check.response:
    status: 200
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://kibana:5601"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  check.request:
    method: "GET"
  check.response:
    status: 200
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://nginx/server-status"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  check.request:
    method: "GET"
  check.response:
    status: 200
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://apache2/server-status"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  check.request:
    method: "GET"
  check.response:
    status: 200
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://logstash:9600"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  check.request:
    method: "GET"
  check.response:
    status: 200
- type: tcp
  enabled: true
  schedule: '@every 5s'
  hosts: ["tcp://mysql:3306"]
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
logging.to_files: false
